### ISSUE TITLE
why do you use envoy

### ISSUE THREAD

**Issue by fizz12344321** [exohood/exohood-envoy-server#57]
Hi, i am reading your project and i love it, can i ask u a question, why do you use Envoy in your project. Can you tell me the purpose, the pros and cons of this. thank u so much

**Comment by ShiraOtsuki** [comment]
Hi, well the firts the envoy is a fantastic tool for creating a huge workplace experience, so we are building a space where users can interact directly with the dev team, also breaking the schemes of closed teams, we think that the review or suggestions are satisfactory but they are not complete if you can be interacting live with the team creativity and the potential for the products would be incredible, so the idea for use envoy is simple "direct connection bridge with the end-user and the development team".
